#Primer curs: Getting Started with Python

##Sessió 1

###Funció $print$ per mostrar text o valors

Les cel·les es poden executar amb shift+enter

In [ ]:
print("hello world")

hello world


In [ ]:
#això és un comentari,com veus el tipus de cometes no afecten
print('hello world')

hello world


###Ús de $input$ per demanar valors i dades mentre s'executa el codi

**Write a program that uses input to prompt a user for their name and then welcomes them. Note that input will pop up a dialog box. Enter Sarah in the pop-up box when you are prompted so your output will match the desired output.**

In [ ]:
"""com veus, si vols ajuntar text amb variables, una manera fàcil de fer-ho és
utilitzant una coma en el codi, que quan s'executi es transformarà en un espai"""
name = input("Enter your name: ")
print("Hello", name)

Enter your name: Arnau
Hello Arnau


**Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Use 35 hours and a rate of 2.75 per hour to test the program (the pay should be 96.25). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking or bad user data.**

In [ ]:
#a mi m'agrada fer funcions per poder reutilitzar codi
#amb el float() transformes a números amb decimals
#hi ha str() per fer strings o int() per truncar números (sense decimals), per exemple int(20.8) dóna 20
hrs = input("Enter Hours:")
paga_hr = input("Enter Salary:")
def paga(hores,paga_hora):
    return print("Pay:",hores*paga_hora)
paga(float(hrs),float(paga_hr))

Enter Hours:35
Enter Salary:2.75
Pay: 96.25


In [ ]:
#també es podia fer directe
hrs2 = input("Enter Hours:")
paga_hr2 = input("Enter Salary:")
print("Pay:",float(hrs2)*float(paga_hr2))

Enter Hours:35
Enter Salary:2.75
Pay: 96.25


##Sessió 2

###Condicionals amb *if* i indexació

Python utilitza indexació així que és important tenir en compte què va dins de què

In [ ]:
#els if ns com van en altres programes però aquí és fàcil
#si la condició se satisfà, fa el que el codi de dins mana,
#si la condició no se satisfà, va a la següent línia de codi
num = input('Tria un número: ')
if float(num)<10:
  print('És menor de 10')
if float(num)>0:
  print('És positiu')
if float(num)<=0:
  print('No és positiu')
#es pot veure que si poses bé l'if i els dos punts, el colaboratory ja t'indexa

Tria un número: 0
És menor de 10
No és positiu


In [ ]:
#per tal que si no se satisfà el if s'executi un altre codi, tens el else
num = input('Tria un número: ')
if float(num)>0:
  print('És positiu')
else:
  print('No és positiu')


Tria un número: 0
No és positiu


###Condicionals amb *elif*

In [ ]:
#si tens un if i vols posar més condicions a part de else, poses un elif
"""tingues en compte que només un de tots els condicionals s'executarà,
si la condició de l'if se satisfà, el elif i el else no es llegiran"""
x = input("Escriu un número: ")
if float(x)<5:
  print('És un número molt petit')
elif float(x)<20:
  print('És un número mitjà')
else:
  print('És un número gran')

Escriu un número: 2
És un número molt petit


In [ ]:
#no cal tenir un else al final si no vols obtenir sempre una resposta,
#sense l'else, quan no es compleixi cap condició simplement no s'executarà res
x = input("Escriu un número: ")
if float(x)<5:
  print('És un número molt petit')
elif float(x)<20:
  print('És un número mitjà')

Escriu un número: 20


In [ ]:
"""pots tenir molts elif seguits, però recorda que a la que un s'executi (i va en ordre)
 la resta de condicions se saltaran i es procedirà a llegir el següent conjunt de codi"""
x = input("Escriu un número: ")
if float(x)<5:
  print('És un número molt petit')
elif float(x)<20:
  print('És un número mitjà')
elif float(x)<50:
 print('És un número gran')
elif float(x)<100:
  print('És un número enorme')
else:
  print("T'has passat tres pobles")
#fixa't que si vols escriure apòstrofs com a string has d'utilitzar les dobles cometes o se't tancarà abans d'hora 

Escriu un número: 3
És un número molt petit


###Com evitar que peti el codi amb *try* i *except*

Pots posar moltes coses dins del *try*, però si algo peta ja no farà res del try i anirà directament al except.

In [ ]:
#això és útil quan no vols que el teu codi peti i deixi de llegir la resta
x = input("Escriu algo: ")
try:
  num = float(x)
  print(num)
except:
  print('No és un número')
print('fi')
#aquí, com que float() converteix una string en número amb decimals, si no s'escriu un número
#com a input, el float() donaria error, però amb l'except diem que si dóna error, enlloc d'explotar
#segueixi el codi de sota

Escriu algo: hola
No és un número
fi


"aquí, com que float() converteix una string en número amb decimals, si no s'escriu un número\ncom a input, el float() donaria error, però amb l'except diem que si dóna error, enlloc d'explotar\nsegueixi el codi de sota"

**Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay the hourly rate for the hours up to 40 and 1.5 times the hourly rate for all hours worked above 40 hours. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input - assume the user types numbers properly.**

In [ ]:
hrs = input("Enter Hours:")
h = float(hrs)
salari = float(input("Enter Hourly Rate: "))
if h<=40:
    tope = salari*h
    print(tope)
else:
    print(1.5*salari*(h-40)+40*salari)

Enter Hours:45
Enter Hourly Rate: 10.50
498.75


**Write a program to prompt for a score between 0.0 and 1.0. If the score is out of range, print an error. If the score is between 0.0 and 1.0, print a grade using the following table:**\
Score Grade
>= 0.9 A\
>= 0.8 B\
>= 0.7 C\
>= 0.6 D\
< 0.6 F\
If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.

In [ ]:
#en aquest exercici, com a extra, he utilitzat operadors lògics "and" que funcionen com a tot arreu
score = input("Enter Score: ")
if float(score)<=1.0 and float(score)>=0.9:
    print("A")
elif float(score)<=1.0 and float(score)>=0.8:
    print("B")
elif float(score)<=1.0 and float(score)>=0.7:
    print("C")
elif float(score)<=1.0 and float(score)>=0.6:
    print("D")
elif float(score)>=0.0 and float(score)<0.6:
    print("F")
else:
    print("Input must be a number between 0.0 and 1.0 both included")

Enter Score: 0.8
B


In [ ]:
def stuff():
    print('Hello')
    return
    print('World')

stuff()

Hello


##Sessió 3

###Creació de funcions

Hi ha més d'una sola manera per crear funcions amb Python, de moment veurem la més intuïtiva.\
Per indicar que comences una funció utilitzes el *def*, seguit del nom de la funció i les variables entre parèntesi. \
Pots voler les funcions per fer tot el que hi poses a dins o bé per imprimir específics valors resultants de càlculs que hi fas. En aquest darrer cas cal acabar el codi indexat dins de *def* amb un *return*.

In [ ]:
def ordre(a,b,c):
  if a<b<c:
    print('Estan ordenats')
  else:
    print('No estan ordenats')

ordre(1,2,3)

Estan ordenats


In [ ]:
def producte(x,y):
  vull = x*y
  return vull

producte(1,2)

2

In [ ]:
#es pot fer encara més curt ja que al return pots posar operacions
def producte(x,y):
  return x*y

producte(1,2)

2

**Write a program to prompt the user for hours and rate per hour using input to compute gross pay. Pay should be the normal rate for hours up to 40 and time-and-a-half for the hourly rate for all hours worked above 40 hours. Put the logic to do the computation of pay in a function called computepay() and use the function to do the computation. The function should return a value. Use 45 hours and a rate of 10.50 per hour to test the program (the pay should be 498.75). You should use input to read a string and float() to convert the string to a number. Do not worry about error checking the user input unless you want to - you can assume the user types numbers properly. Do not name your variable sum or use the sum() function.**

In [ ]:
#per la part condicional podem reutilitzar el codi de la sessió 2
def computepay(h,r):
    if h<=40:
    	return r*h
    else:
    	return 1.5*r*(h-40)+40*r

hrs = input("Enter Hours:")
salari = input("Enter Hourly Rate: ")
p = computepay(float(hrs),float(salari))
print("Pay",p)

Enter Hours:45
Enter Hourly Rate: 10.50
Pay 498.75


##Sessió 4

###Loops infinits o condicionals amb el *while*

Comencem veient el *while*, això funciona com un if (és a dir té una condició) però quan arriba a l'última línia indexada (executada si la condició és certa) enlloc de passar a la següent línia torna a la primera dins del *while*, i així fins que la condició deixa de complir-se.

In [ ]:
cuenta_atras = int(input("Escriu un número des d'on contar fins a 0: "))
while cuenta_atras>-1:
  print(cuenta_atras)
  cuenta_atras = cuenta_atras - 1
#hi ha una manera més còmoda d'anar restant -1, seria x-=1

Escriu un número des d'on contar fins a 0: 4
4
3
2
1
0


Per evitar els loops infinits o per tornar a l'inici dels *while*'s tenim els comandos *break* per parar i *continue* per seguir.

In [ ]:
"""aquest codi té més chicha, al while posem True, que és una funció lògica ja inclosa
a Python, per tant el while serà un loop infinit (ja que no ho podem canviar a False)
És fàcil veure que text[0] és el primer terme de l'string de l'input, si és un #, no farem
res sinó que tornarem a demanar un input, si l'input és igual a 'Para' el que farà serà sortir
del while i seguir amb el codi de sota. Nota que per aplicar la condició de que una cosa és igual
a una altra utilitzem == (no =), és un altre tipus de condició, com bé serien <,>, etc."""

while True:
  text = input('Escriu algo: ')
  if text[0] == '#':
    continue
  if text == 'Para':
    break
  print(text)
print('Ja has acabat:)')

Escriu algo: Hola
Hola
Escriu algo: # modo incognito
Escriu algo: Para
Ja has acabat:)


###Loops finits amb el *for*

In [ ]:
#recordem que [] és una llista
for i in [5,4,3,2,1]:
  print(i)
print('fi')

5
4
3
2
1
fi


In [ ]:
for familiar in ['Javi', 'Marta', 'Arnau', 'Oriol', 'Eudald']:
  print('Està al grup de Liras:',familiar)

Està al grup de Liras: Javi
Està al grup de Liras: Marta
Està al grup de Liras: Arnau
Està al grup de Liras: Oriol
Està al grup de Liras: Eudald


In [ ]:
#també et pots definir la llista abans
familiars = ['Javi', 'Marta', 'Arnau', 'Oriol', 'Eudald']
for familiar in familiars:
  print('Està al grup de Liras:',familiar)


Està al grup de Liras: Javi
Està al grup de Liras: Marta
Està al grup de Liras: Arnau
Està al grup de Liras: Oriol
Està al grup de Liras: Eudald


Evidentment dins de loops es poden posar condicionals i altres objectes estudiats, així que passo directament a fer exercicis.

**Write a program that repeatedly prompts a user for integer numbers until the user enters 'done'. Once 'done' is entered, print out the largest and smallest of the numbers. If the user enters anything other than a valid number catch it with a try/except and put out an appropriate message and ignore the number. Enter 7, 2, bob, 10, and 4 and match the output below.**

In [ ]:
largest = None
smallest = None
while True:
    try:
      num = input("Enter a number: ")
      if num == 'done':
        break
      elif smallest == None:
        smallest = int(num)
        largest = int(num)
      elif int(num)<smallest:
        smallest = int(num)
      elif int(num)>largest:
        largest = int(num)
    except:
      print('Invalid input')
      continue

print("Maximum is", largest)
print("Minimum is", smallest)

Enter a number: 7
Enter a number: 2
Enter a number: bob
Invalid input
Enter a number: 10
Enter a number: 4
Enter a number: done
Maximum is 10
Minimum is 2


#Segon curs: Python Data Structures

##Sessió 1

###Strings: *len( )*, slicing, operador lògic *in*, etc.

In [ ]:
#segurament ja les coneixes, seria l'equivalent a tenir text,
#tot i que un seguit de números també pot ser una string

#es poden sumar
string1 = 'Hello'
string2 = ' World'
print(string1+string2)

Hello World


In [ ]:
#si vols sumar números has de vigilar de no tenir-los com a string
#recorda que el try s'executa si tot va bé, si dóna error salta l'except
try:
  str3 = '12'
  print(str3+1)
  print('Sí es pot sumar')
except:
  str3 = '12'
  print(int(str3)+1)
  print('Cal convertir la string en un integrer o float per poder sumar')

13
Cal convertir la string en un integrer o float per poder sumar


També cal recordar que tots els inputs són de tipus string: 

In [ ]:
#aprofitem per veure la funció interna type() per saber quin tipus d'objecte tenim
x = input('Escriu algo: ')
if type(x) == str:
  print('És una string')
else:
  print('No és una string')

Escriu algo: blablabla
És una string


Ara veurem com jugar una mica amb els elements de una string, serà semblant al tractament de llistes que segurament farem més endavant.

In [ ]:
#important recordar que el primer terme és el 0
#veiem que "nom de la string"[número] ens dóna aquell element de la string
#notar també que si ens passem, no torna al principi (no és cíclic) sinó que donarà error
fruit = 'banana'
lletra_u = fruit[0]
lletra_dos = fruit[1]
print(lletra_u)
print(lletra_dos)

b
a


####*len( )*

In [ ]:
#per saber la longitud d'una cadena (string) hi ha la funció interna len(string)
fruit = 'banana'
llargada = len(fruit)
print(llargada)

6


In [ ]:
fruit = 'banana'
index = 0
while index < len(fruit):
  print(index,fruit[index])
  index +=1
#recordem que això últim equivaldria a posar index = index + 1
#són truquitos interessants hehe

0 b
1 a
2 n
3 a
4 n
5 a


T'ensenyo el *while* per anar repassant i perquè surt al curs, però amb el for queda millor:

In [ ]:
#recordem que amb el for és fàcil manar on començar, on acabar i ell sol
#ja et va actualitzant el compte del que sigui per avançar cap a un final
fruit = 'banana'
for i in fruit:
  print(i)

b
a
n
a
n
a


####Slicing

Slicing bàsicament vol dir **tallar**, és molt senzill tot i que pot costar acostumar-se als índexs. string[0:4] per exemple ens donaria des del primer terme fins al anterior del que es troba en posició 4 (la posició 4, al començar al 0, és el cinquè
$\implies$ ens donarà des del primer al quart element.

In [ ]:
fruit = 'bananas are yellow'
print(fruit[0:4])

bana


In [ ]:
#si et passes d'index, en aquesta situació no passa res, no dóna error
paraula_curta = 'this is short'
print(paraula_curta[3:400])

s is short


No sempre cal posar els índexs, si vols començar al principi, acabar al final o agafar-ho tot, no cal posar res:)

In [ ]:
st = '1234567890'
print('Des del principi al 5è terme seria així:', st[:5])
print('Des del 5è terme al final seria així:', st[4:])
print('Tots els termes serien així:', st[:], '. O bé així:', st)

Des del principi al 5è terme seria així: 12345
Des del 5è terme al final seria així: 567890
Tots els termes serien així: 1234567890 . O bé així: 1234567890


####Operador lògic *in*

In [ ]:
#hem utilitzat ja in per processos iteratius, tembé el podem fer servir 
#en condicionals com a operador lògic
color = 'blau'
if 'a' in color:
  print('té una a')

té una a


###Manipulating strings

####Funcions internes per strings

In [ ]:
#la funció string.lower() t'ho passa tot a minúscula
frase = 'Hola el meu nom és Arnau i sóc de Terrassa'
minus = frase.lower()
print(minus)

#fixa't que no et modifica la string que tens sinó que crea una còpia
#si modifiqués la string, ara sortiria en minúscules
print(frase)

#també funciona amb una string directament
print('Minúscules DirectaMent'.lower())

#el contrari seria string.upper()
frase2 = 'ale posa això en majúscules'
print(frase2.upper())

hola el meu nom és arnau i sóc de terrassa
Hola el meu nom és Arnau i sóc de Terrassa
minúscules directament
ALE POSA AIXÒ EN MAJÚSCULES


Com hem vist anteriorment, *type(objecte)* et diu el tipus d'objecte, pot ser una funció, integrer, float, string...
Per saber què podem fer amb un objecte (funcions internes) tenim el *dir(objecte)* que ens dóna totes les possibilitats. SI tenim curiositat sobre alguna només cal googlejar-la.
https://docs.python.org/3/library

In [ ]:
llibre = '¿Está usted de broma, Sr. Feynman?'
type(llibre)
dir(llibre)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

Altres opcions són:

In [ ]:
print('aquesta posa en majúscula només la primera'.capitalize())
print('EXEmPLE SECunDARI'.capitalize())

Aquesta posa en majúscula només la primera
Exemple secundari


In [ ]:
#molt rellevant, string.find()
#aquesta és com l'in però enlloc de dir si la cosa està a dins o no,
#et diu a quina posició està, i si no ho troba torna un -1
#només troba un cop l'element que li dius, el primer lloc on apareix
print("A veure si trobes alguna i".find('i'))
print("A ver si trobes la segona lletra del nom de l'enano".find('u'))

9
-1


In [ ]:
#també rellevant string.replace()
#busca i substitueix a tot arreu on troba la entrada
#fa una còpia de l'original, aquesta no te la toca
z = 'Hello World'
print(z.replace('o', 'x'))


Hellx Wxrld


In [ ]:
#per eliminar "whitespaces", per exemple els espais, hi ha tmb funcions
#pots eliminar espais a la dreta, a l'esquerra o tots
saludo = '  Buenas papa     '
print(saludo.lstrip()) #treu a l'esquerra (left)
print(saludo.rstrip())  #treu a la dreta (right)
print(saludo.strip()) #treu els de les dues bandes

Buenas papa     
  Buenas papa
Buenas papa


In [ ]:
#per trobar prefixos
y = 'Ja ns què més posar'
print(y.startswith('Ja ns'))
print(y.startswith('j')) #majúscules i minúscules es diferencien

True
False


Si per exemple vull trobar un tros de text i conec quines característiques ha de tenir, com el final d'un correu electrònic:

In [ ]:
mail = "El meu correu és tal.pasqual@mail.cat i m'hi connecto cada dia"
inici = mail.find('@')
final = mail.find(' ', inici) #li puc dir on vull que comenci a buscar
print(mail[inici+1:final])

mail.cat


####Exercici final

**Write code using find() and string slicing (see section 6.10) to extract the number at the end of the line below. Convert the extracted value to a floating point number and print it out.**

In [ ]:
text = "X-DSPAM-Confidence:    0.8475";
inici = text.find('0')
print(float(text[inici:]))

0.8475


##Sessió 2

Sessió 3 del curs, la 2 era sobre instalar python i fer captures de pantalla.

In [ ]:
text = "aixo $\\$ es un text $\\$ amb unes linies $\\$ diferents en cada $\\$ cas"
count=0
for line in text:
  count=count+1

print(count)

#caldria tenir text=open(document) i contaria línies enlloc de termes
#es poden posar if amb per exemple line.startswith(' amb') per imprimir només certes línies
#si imprimeixes línies i surten molt separades cal un line.rstrip() per eliminar el salt de línia,
#el print() ja en posa un i es dupliquen

69


###Entrega 1 de la setmana

 Write a program that prompts for a file name, then opens that file and reads through the file, and print the contents of the file in upper case. Use the file words.txt to produce the output below.
You can download the sample data at http://www.py4e.com/code3/words.txt

In [ ]:
# Use words.txt as the file name
fname = input("Enter file name: ")
fh = open(fname)
for line in fh:
    line=line.rstrip().upper()
    print(line)

Enter file name: words.txt
WRITING PROGRAMS OR PROGRAMMING IS A VERY CREATIVE
AND REWARDING ACTIVITY  YOU CAN WRITE PROGRAMS FOR
MANY REASONS RANGING FROM MAKING YOUR LIVING TO SOLVING
A DIFFICULT DATA ANALYSIS PROBLEM TO HAVING FUN TO HELPING
SOMEONE ELSE SOLVE A PROBLEM  THIS BOOK ASSUMES THAT
{\EM EVERYONE} NEEDS TO KNOW HOW TO PROGRAM AND THAT ONCE
YOU KNOW HOW TO PROGRAM, YOU WILL FIGURE OUT WHAT YOU WANT
TO DO WITH YOUR NEWFOUND SKILLS

WE ARE SURROUNDED IN OUR DAILY LIVES WITH COMPUTERS RANGING
FROM LAPTOPS TO CELL PHONES  WE CAN THINK OF THESE COMPUTERS
AS OUR PERSONAL ASSISTANTS WHO CAN TAKE CARE OF MANY THINGS
ON OUR BEHALF  THE HARDWARE IN OUR CURRENT-DAY COMPUTERS
IS ESSENTIALLY BUILT TO CONTINUOUSLY ASK US THE QUESTION
WHAT WOULD YOU LIKE ME TO DO NEXT

OUR COMPUTERS ARE FAST AND HAVE VASTS AMOUNTS OF MEMORY AND
COULD BE VERY HELPFUL TO US IF WE ONLY KNEW THE LANGUAGE TO
SPEAK TO EXPLAIN TO THE COMPUTER WHAT WE WOULD LIKE IT TO
DO NEXT IF WE KNEW THIS LANGUAGE WE COULD TEL

###Entrega 2 de la setmana

Write a program that prompts for a file name, then opens that file and reads through the file, looking for lines of the form:
X-DSPAM-Confidence:    0.8475
Count these lines and extract the floating point values from each of the lines and compute the average of those values and produce an output as shown below. Do not use the sum() function or a variable named sum in your solution.
You can download the sample data at http://www.py4e.com/code3/mbox-short.txt when you are testing below enter mbox-short.txt as the file name.

In [ ]:
# Use the file name mbox-short.txt as the file name
fname = input("Enter file name: ")
fh = open(fname)
valor=0
count=0
for line in fh:
    if line.startswith("X-DSPAM-Confidence:"):
    	inici= line.find(':')+1
    	valor=valor+float(line[inici:])
    	count=count+1
    else:
        continue
average=valor/count    
print("Average spam confidence:",average)

Enter file name: mbox-short.txt
Average spam confidence: 0.7507185185185187


##Sessió 3

###Llistes

Són col·leccions d'una sola variable, s'expressen entre [ ]. Els elements en una llista se separen per comes (,), podem tenir tot tipus d'objectes dins de llistes, fins i tot altres llistes. També existeixen llistes buides. \\
Recordem que tot i que $strings$ no són mutables, les llistes sí ho són. 

In [ ]:
buida=[]
print(len(buida)) #per saber quants elements tenim a la llista

buida2=list()
print(len(buida2))

0
0


In [ ]:
#recordem que les llistes es poden cridar per indexs
list=[1,2,3,4,5,6,7,8,9]
print('Primer terme:',list[0], ', del 2n al 4t terme:', list[2:5], ', últim terme:', list[-1])
print('Intervals de termes:', list[:6])
print(list[2:])
#com s'ha vist abans, el darrer terme  indica "fins aquí però sense incloure'l"

Primer terme: 1 , del 2n al 4t terme: [3, 4, 5] , últim terme: 9
Intervals de termes: [1, 2, 3, 4, 5, 6]
[3, 4, 5, 6, 7, 8, 9]


####Suma de llistes

In [ ]:
#se sumen com les strings
a=[1,2,3]
b=[6,7,8]
print(a+b)

[1, 2, 3, 6, 7, 8]


####Funció *range( )* i *len( )*

In [ ]:
llista = [3,4,5]
print(range(len(llista))) #comença contant per 0 i fins al nombre final que es posa-1

range(0, 3)


In [ ]:
familia = ['Javi', 'Oriol', 'Eudald', 'Marta']
for i in familia:
  print('Feliç pany nou', i)
for i in range(len(familia)):
  membre=familia[i]
  print('Feliç pany deu', membre)


Feliç pany nou Javi
Feliç pany nou Oriol
Feliç pany nou Eudald
Feliç pany nou Marta
Feliç pany deu Javi
Feliç pany deu Oriol
Feliç pany deu Eudald
Feliç pany deu Marta


####*.append( )* i *.sort( )*

In [ ]:
#llista.append(coses) per afegir coses al final de la llista
nj = []
dir(nj)
nj.append('bjl')
nj.append('ahjb')
nj.append('bji')
#per odenar llista.sort()
print(1,nj.sort()) #no funciona així, cal donar-li un nom
nj.sort()
print(2,nj)

1 None
2 ['ahjb', 'bji', 'bjl']


####Altres: *max( )*, *min( )*, *sum( )*

In [ ]:
perfer_mitjana = [3,5,4,5,56,43,23,11]
print('Màxim:', max(perfer_mitjana))
print('Mínim:', min(perfer_mitjana))
print('Suma:', sum(perfer_mitjana))
print('Mitjana:', sum(perfer_mitjana)/len(perfer_mitjana))

Màxim: 56
Mínim: 3
Suma: 150
Mitjana: 18.75


###Llistes i strings

In [ ]:
#de string a llista
string = 'this     is a string'
print(len(string))
llista = string.split()  #talla pels espais, si hi ha múltiples espais els talla tots
print(llista)
string2 = 'this;is;a;string'
print(len(string2))
llista2 = string2.split(';')  #talla pel que tu diguis
print(llista2)

20
['this', 'is', 'a', 'string']
16
['this', 'is', 'a', 'string']


###Entrega 1 de la setmana

8.4 Open the file romeo.txt and read it line by line. For each line, split the line into a list of words using the split() method. The program should build a list of words. For each word on each line check to see if the word is already in the list and if not append it to the list. When the program completes, sort and print the resulting words in alphabetical order.
You can download the sample data at http://www.py4e.com/code3/romeo.txt

In [ ]:
fname = input("Enter file name: ")
fh = open(fname)
lst = list()
for line in fh:
    for item in line.split():
        if not item in lst:
            lst.append(item)
lst.sort()
print(lst)

Enter file name: romeo.txt
['Arise', 'But', 'It', 'Juliet', 'Who', 'already', 'and', 'breaks', 'east', 'envious', 'fair', 'grief', 'is', 'kill', 'light', 'moon', 'pale', 'sick', 'soft', 'sun', 'the', 'through', 'what', 'window', 'with', 'yonder']


###Entrega 2 de la setmana

Open the file mbox-short.txt and read it line by line. When you find a line that starts with 'From ' like the following line:
From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008
You will parse the From line using split() and print out the second word in the line (i.e. the entire address of the person who sent the message). Then print out a count at the end.
Hint: make sure not to include the lines that start with 'From:'.

You can download the sample data at http://www.py4e.com/code3/mbox-short.txt

In [ ]:
fname = input("Enter file name: ")
if len(fname) < 1 : fname = "mbox-short.txt"

fh = open(fname)
count = 0

for line in fh:
    if line.startswith('From '):
        llista = line.split()
        print(llista[1])
        count=count+1
    
print("There were", count, "lines in the file with From as the first word")


Enter file name: mbox-short.txt
stephen.marquard@uct.ac.za
louis@media.berkeley.edu
zqian@umich.edu
rjlowe@iupui.edu
zqian@umich.edu
rjlowe@iupui.edu
cwen@iupui.edu
cwen@iupui.edu
gsilver@umich.edu
gsilver@umich.edu
zqian@umich.edu
gsilver@umich.edu
wagnermr@iupui.edu
zqian@umich.edu
antranig@caret.cam.ac.uk
gopal.ramasammycook@gmail.com
david.horwitz@uct.ac.za
david.horwitz@uct.ac.za
david.horwitz@uct.ac.za
david.horwitz@uct.ac.za
stephen.marquard@uct.ac.za
louis@media.berkeley.edu
louis@media.berkeley.edu
ray@media.berkeley.edu
cwen@iupui.edu
cwen@iupui.edu
cwen@iupui.edu
There were 27 lines in the file with From as the first word


##Sessió 4

###Diccionaris

Llista: Col·lecció lineal de valors que es mantenen en ordre. Indexen els elements segons la posició a la llista.

Diccionari: "Bossa" de valors, cada una amb una etiqueta. No tenen ordre, els elements estan indexats amb un "lookup tag".

In [ ]:
#les llistes es feien amb [], els diccionaris es fan amb {}
dicc = {}
dicc2 = dict() #diferents maneres de crear diccionaris buits
dicc['diners'] = 21  #així s'afegeixen elements al dicc o es modifiquen
dicc['elemets'] = 118
print(dicc)
print(dicc['diners'])
dicc['diners']+=2  #equivalent a dicc['diners']=dicc['diners'] + 2
print(dicc['diners'])

{'diners': 21, 'elemets': 118}
21
23


In [ ]:
#per veure si un element està en un diccionari: (executar línia anterior primer de tot)
print('diners' in dicc)
print('random' in dicc)


True
False


In [ ]:
contar = {}
noms = ['a','b','c', 'a', 'c']
for nom in noms:
  if nom not in contar:
    contar[nom] = 1
  else:
    contar[nom]+=1
print(contar)

{'a': 2, 'b': 1, 'c': 2}


####*.get( )*

In [ ]:
contar = {}
noms = ['a','b','c', 'a', 'c']
for nom in noms:
  contar[nom] = contar.get(nom, 0) + 1
print(contar)

{'a': 2, 'b': 1, 'c': 2}


Contar paraules:

In [ ]:
cont = {}
linia = input('Write a sentence: ')
paraules = linia.split()
print('Paraules:', paraules)
print('Contant...')
for paraula in paraules:
  cont[paraula] = cont.get(paraula, 0) + 1

print('Recompte:', cont)

Write a sentence: vaja vaja quina frase posarem que estigui com repetida com molts cops
Paraules: ['vaja', 'vaja', 'quina', 'frase', 'posarem', 'que', 'estigui', 'com', 'repetida', 'com', 'molts', 'cops']
Contant...
Recompte: {'vaja': 2, 'quina': 1, 'frase': 1, 'posarem': 1, 'que': 1, 'estigui': 1, 'com': 2, 'repetida': 1, 'molts': 1, 'cops': 1}


####Loops dins de diccionaris

In [ ]:
noms = {}
noms['a']=2
noms['b']=4
noms['c']=3
for clau in noms:
  print(clau, noms[clau])

a 2
b 4
c 3


####Com obtenir claus i valors dels diccionaris

In [ ]:
noms = {'a':2, 'b':4, 'c':3}
#obtenir les claus aka noms
print(list(noms))
#obtenir les claus de manera diferent
print(noms.keys())
#obtenir els valors
print(noms.values())
#obtenir els elements com a 'tuples'
print(noms.items())

['a', 'b', 'c']
dict_keys(['a', 'b', 'c'])
dict_values([2, 4, 3])
dict_items([('a', 2), ('b', 4), ('c', 3)])


####Bonus: iteració amb dues variables

In [ ]:
noms = {'a':2, 'b':4, 'c':3}
for x,y in noms.items():
  print(x,y)

a 2
b 4
c 3


In [ ]:
stuff = dict()
print(stuff.get('candy',-1))

-1


###Entrega de la setmana

Write a program to read through the mbox-short.txt and figure out who has sent the greatest number of mail messages. The program looks for 'From ' lines and takes the second word of those lines as the person who sent the mail. The program creates a Python dictionary that maps the sender's mail address to a count of the number of times they appear in the file. After the dictionary is produced, the program reads through the dictionary using a maximum loop to find the most prolific committer.

In [ ]:
name = input("Enter file:")
if len(name) < 1 : name = "mbox-short.txt"
handle = open(name)
dic = {}
for line in handle:
    if line.startswith('From '):
        paraules = line.split()
        dic[paraules[1]] = dic.get(paraules[1], 0) + 1
    else:
        continue
bigcount = 0
bigword = None
for paraula,num in dic.items():
    if num > bigcount:
        bigword = paraula
        bigcount = num
    else:
        continue

print(bigword, bigcount)

Enter file:mbox-short.txt
cwen@iupui.edu 5


##Sessió 5

###Tuples

Són com llistes: seqüència d'elements ordenats que comença per índex 0

In [ ]:
x = ('a', 'b', 'c', 'd')
y = (1,2,3,4,4)
for i in x:
  print(i)
print(max(y))
print(y)

a
b
c
d
4
(1, 2, 3, 4, 4)


####Diferència resp. llistes

La diferència amb les llistes és que $tuples$ són immutables

In [ ]:
#recordem que si no hi ha error s'executarà el try, però si el try conté un error
#s'executarà el except
y=(4,2,7,95,54,23)
z=[4,2,7,95,54,23]
try:
  z[1]=3
  print('Es pot canviar en una llista: ', z[1])
except:
  print('No es pot canviar en una llista')
try:
  y[1]=3
  print('Es pot canviar en una tuple: ', y[1])
except:
  print('No es pot canviar en una tuple')

Es pot canviar en una llista:  3
No es pot canviar en una tuple


Altres coses pohibides en tuples i legals en llistes

In [ ]:
tup = (3,2,1)
try:
  x.sort()
except:
  print('No es poden reordenar')
try:
  x.append()
except:
  print('No es poden afegir termes al final')
try:
  x.reverse()
except:
  print('No es poden invertir')

No es poden reordenar
No es poden afegir termes al final
No es poden invertir


In [ ]:
t = tuple()
dir(t)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

Com que són immutables, la seva efinciència en despesa de computació és molt major. Seran preferibles a les llistes quan la seva funcionalitat ja ens serveixi per la necessitat que ens cal cobrir.

In [ ]:
#podem tenir dobles tuples per assignar valors
(x,y) = (3,6)
print(y)
(k,m) = ('hehe', 2)
print(k)

6
hehe


In [ ]:
#tuples & dictionaries
#recordem que el diccionari.items() retorna tuples:
d = {}
d['a']=2
d['b']=22
for (x,y) in d.items():
  print(x,y)

print(d.items())

a 2
b 22
dict_items([('a', 2), ('b', 22)])


####Comparació de tuples

In [ ]:
#són comparables
print((1,2,3)<(2,3,4))
print((5,6,7)<(3,4,5))
print((1,2,3)<(2,1,1))

True
False
True


####Ordenar llistes de tuples amb *sorted( )*

In [ ]:
di = {'a':1,'s':4,'d':21,'f':7,'g':5}
o = sorted(di.items())
print(o)
for x,y in o:
  print(x,y)
#ordenar al revés
r = sorted(di.items(), reverse =True) 
print(r)
#ordenem per valors
p = []
for x,y in di.items():
  p.append((y,x))
print(sorted(p, reverse = True))

[('a', 1), ('d', 21), ('f', 7), ('g', 5), ('s', 4)]
a 1
d 21
f 7
g 5
s 4
[('s', 4), ('g', 5), ('f', 7), ('d', 21), ('a', 1)]
[(21, 'd'), (7, 'f'), (5, 'g'), (4, 's'), (1, 'a')]


####Exercici: Top paraules més utilitzades

In [ ]:
frase = input('Escriu una frase')
counts = {}
paraules = frase.split()
for paraula in paraules:
  counts[paraula] = counts.get(paraula,0) + 1

lst = []
for key,val in counts.items():
  tup = (val,key)
  lst.append(tup)
lst = sorted(lst, reverse = True)
for val, key in lst[:10]:
  print(key, val)

Escriu una fraseque wtf vaja que random per que estic escrivint aquesta frase que no recordare per no
que 4
per 2
no 2
wtf 1
vaja 1
recordare 1
random 1
frase 1
estic 1
escrivint 1


In [ ]:
#reduint linies de codi
c = {'a':10, 'b':3, 'c':947}
print( sorted( [(v,k) for k,v in c.items()]))
#creem una llista de tuples invertits i la ordenem

[(3, 'b'), (10, 'a'), (947, 'c')]


###Entrega de la setmana

Write a program to read through the mbox-short.txt and figure out the distribution by hour of the day for each of the messages. You can pull the hour out from the 'From ' line by finding the time and then splitting the string a second time using a colon.

From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008

Once you have accumulated the counts for each hour, print out the counts, sorted by hour as shown below.

In [ ]:
name = input("Enter file:")
if len(name) < 1 : name = "mbox-short.txt"
handle = open(name)
dic = {}
for line in handle:
    if line.startswith('From '):
        words = line.split()
        temps = words[-2]
        hores = temps.split(':')
        hora = hores[0]
        dic[hora] = dic.get(hora, 0) + 1
lst = []
for key,value in dic.items():
	tup = (key,value)
	lst.append(tup)
lst = sorted(lst)
for key, val in lst:
    print(key,val)

Enter file:mbox-short.txt
04 3
06 1
07 1
09 2
10 3
11 6
14 1
15 2
16 4
17 2
18 1
19 1


#Tercer curs: Using Python to Access Web Data

##Sessió 1

###Guia ràpida de $\mathbf{Regular \:Expressions}$:

Cal importar re (import re):

^: Encaixa l'**inici** d'una línia

$: Encaixa el **final** d'una línia

.: Encaixa **qualsevol** caràcter

\s: Encaixa **espais en blanc**

\S: Encaixa **qualsevol caràcter DIFERENT a espais en blanc**

*: Repeteix un caràcter 0 o més vegades

*?: Repeteix un caràcter 0 o més vegades (non-greedy)

+: Repeteix un caràcter 1 o més vegades

+?: Repeteix un caràcter 1 o més vegades (non-greedy)

[aeiou]: Encaixa un sol caràcter de la llista

[^XYZ]: Encaixa un sol caràcter que **NO pertany** a la llista

[a-z0-9]: El conjunt de caràcters pot incloure un rang

(: Indica on l'extracció de la *string* ha de començar

): Indica on l'extracció de la *string* ha d'acabar

**non-greedy**, com literalment podria ser traduït, vol dir "no avariciós". És a dir, agafarà la cerca només un cop, no tots, o bé el resultat amb menor nombre de repeticions de tots els trobats.


####Exemples

In [ ]:
import re
x = 'X-Sieve: CMU SIeve 2.3'
y = 'X-DSPAM-Result: Innocent'
z = 'X-Plane is behind schedule: two weeks'
x1 = re.findall('^X-\S+:',x) #encaixar X a l'inici de la línia, encaixar qualsevol caràcter no-espai en blanc  1 o més vegades, fins als dos punts(:)
y1 = re.findall('^X-\S+:',y)
z1 = re.findall('^X-\S+:',z)
x2 = re.findall('^X.*:', x) #encaixar X a l'inici, encaixar qualsevol caràcter 0 o més vegades fins als dos pnts(:)
y2 = re.findall('^X.*:', y)
z2 = re.findall('^X.*:', z)
print(x1,y1,z1)
print(x2,y2,z2)

['X-Sieve:'] ['X-DSPAM-Result:'] []
['X-Sieve:'] ['X-DSPAM-Result:'] ['X-Plane is behind schedule:']


In [ ]:
#veiem que * i + són greedy ja que agafen tan enllà com poden
import re
x = 'From: Using the : character'
y_greedy = re.findall('^F.+:', x)
y_non_greedy = re.findall('^F.+?:',x)
print(y_greedy)
print(y_non_greedy)

['From: Using the :']
['From:']


In [ ]:
x= 'From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008'
y = re.findall('\S+?@\S+',x) #almenys un terme no-espai blanc i una @ entremig
#els parèntesi no són part de la cerca però indiquen on iniciar i finalitzar la cerca:
z = re.findall('^From (\S+@\S+)',x)
print(y)
print(z)
y==z

['stephen.marquard@uct.ac.za']
['stephen.marquard@uct.ac.za']


True

####Diferència *re.search( )* i *re.findall( )*

*search* serveix com a operador lògic que retorna True/False, en canvi, *findall* retorna els resultats que encaixen amb la cerca.

In [ ]:
import re
x = 'Els meus 3 números preferits són 8, 57 i 911'
if re.search('[0-9]',x):
  y = re.findall('[0-9]+',x)
  print('Els números presents són:',y)
else:
  print('No hi ha números')
#findall pot tornar 0 termes:
z = re.findall('[AMHJBIOU]', x) #busca les majúscules dins la llista a la string x
print(z)

Els números presents són: ['3', '8', '57', '911']
[]


###Ús de les posicions en *strings*

In [ ]:
data= 'From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008'
atpos = data.find('@')
print(atpos)
sppos = data.find(' ',atpos)
print(sppos)
host = data[atpos+1 : sppos]
print(host)

21
31
uct.ac.za


####Double Split Pattern

In [ ]:
#a vegades interessa tallar de certa manera i agafar-ne una part i tornar a tallar
data= 'From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008'
words = data.split()
email = words[1]
pieces = email.split('@')
print(email)
print(pieces)
print(pieces[1])

stephen.marquard@uct.ac.za
['stephen.marquard', 'uct.ac.za']
uct.ac.za


Versió Regex (Regular Expressions)

In [ ]:
data= 'From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008'
import re
y = re.findall('@([^ ]*)', data) #anar per l'string i buscar @, encaixa terme no-blanc, tants com sigui i pels () extreu els termes no-blanc
z = re.findall('^From.*@([^ ]+)', data)
print(y)
y==z

['uct.ac.za']


True

Spam confidence

In [ ]:
import re
hand = open('mbox-short.txt')
numlist = list()
for line in hand:
  line = line.rstrip()
  stuff = re.findall('^X-DSPAM-Confidence: ([0-9.]+)', line)
  if len(stuff) != 1 : continue
  num = float(stuff[0])
  numlist.append(num)
print('Maximum: ', max(numlist))

In [ ]:
text = """Why should you learn to write programs? 7746
12 1929 8827
Writing programs (or programming) is a very creative 
7 and rewarding activity.  You can write programs for 
many reasons, ranging from making your living to solving
8837 a difficult data analysis problem to having fun to helping 128
someone else solve a problem.  This book assumes that 
everyone needs to know how to program ..."""
import re
nums = re.findall('[0-9]+',text)
for num in range(len(nums)):
  nums[num]=float(nums[num])
print(sum(nums))

27486.0


###Entrega de la setmana

Sample data: http://py4e-data.dr-chuck.net/regex_sum_42.txt (There are 90 values with a sum=445833)

Actual data: http://py4e-data.dr-chuck.net/regex_sum_721149.txt (There are 106 values and the sum ends with 654)


The basic outline of this problem is to read the file, look for integers using the re.findall(), looking for a regular expression of '[0-9]+' and then converting the extracted strings to integers and summing up the integers.

In [ ]:
import re
text = open('regex_sum_721149.txt')
nums = re.findall('[0-9]+',text.read())
for num in range(len(nums)):
  nums[num]=float(nums[num])
print(sum(nums))

473654.0


## Sessió 2

###HTTP Request amb Python

S'utilitzen *sockets* i el port TCP (Transport Control Protocol) utilitzat és el 80 (HTTP).

S'utilitza *.connect( ('host', port) )* per rebre suport de TCP sockets ja de Python:

In [ ]:
#això és un exemple de programa que segueix (socket->connect->send->recv)->Port 80 -> Web pages amb la llibreria socket
import socket
mysock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
mysock.connect(('data.pr4e.org', 80)) #primer el host i dsp el port
cmd = 'GET http://data.pr4e.org/romeo.txt HTTP/1.0\r\n\r\n'.encode()
mysock.send(cmd)
#part on es descodifiquen les dades en el conjunt de caràcters (explicats dsp) i poder-ho representar com a string en Python:
while True:
  data = mysock.recv(512)
  if (len(data)<1):
    break
  print(data.decode())
mysock.close()

HTTP/1.1 200 OK
Date: Sat, 27 Jun 2020 16:26:52 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Sat, 13 May 2017 11:22:22 GMT
ETag: "a7-54f6609245537"
Accept-Ranges: bytes
Content-Length: 167
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Connection: close
Content-Type: text/plain

But soft what light through yonder window breaks
It is the east and Juliet is the sun
Arise fair sun and kill the envious moon
Who is already s
ick and pale with grief



###American Standard Code for Information Interchange (ASCII)

* És una llista de caràcters amb un número associat del 0 al 256 que s'emmagatzemen en 8 bits (0's i 1's), es pot veure una part a: http://www.catonmat.net/download/ascii-cheat-sheet.png
* 8 bits equivalen a 1 byte
* La funció *ord()* retorna el valor numèric d'un caràcter senzill de ASCII

In [ ]:
print(ord('H'))
print(ord('e'))
print(ord('\n'))
print(ord('&'))

72
101
10
38


Tot i així, actualment els caràcter més utilitzats són UTF-8 (entre 1 i 4 bytes) ja que mostra una alta compatibilitat amb ASCII i és una pràctica recomanada per codificar dades que hagin de ser intercanviades entre sistemes.

A Python 3 totes les *strings* són Unicode, es passen a bytes mitjançant la part de codi anteior, on s'especifica.

En resum, *.decode()* torna una string a partir de bytes i *.encode()* retorna la versió codificada d'una string en forma de bytes. Les dues opcions utilitzen utf-8 de manera predeterminada.

En resum:

$\text{1) String unicode}\xrightarrow{encode()}\text{2) Bytes|UTF-8}\xrightarrow{send()}\text{3) Socket(Network)}$

$\text{3) Socket(Network)}\xrightarrow{recv()}\text{2) Bytes|UTF-8}\xrightarrow{decode()}\text{1) String Unicode}$

###Using *urllib* in Python

Ja que HTTP és tan comú, existeix una llibreria que fa tot el treball de *socket* per nosaltres i fa que les pags. web tinguin aparença de fitxer.

In [ ]:
import urllib.request, urllib.parse, urllib.error
fhand = urllib.request.urlopen('http://data.pr4e.org/romeo.txt')
#per mostrar-ho tot:
for line in fhand:
  print(line.decode().strip())

But soft what light through yonder window breaks
It is the east and Juliet is the sun
Arise fair sun and kill the envious moon
Who is already sick and pale with grief


In [ ]:
import urllib.request, urllib.parse, urllib.error
fhand = urllib.request.urlopen('http://data.pr4e.org/romeo.txt')
#contem paraules (ja hem vist com a sessions anteriors):
counts = {}
for line in fhand:
  words = line.decode().split()
  for word in words:
    counts[word] = counts.get(word, 0) + 1
print(counts)

{'But': 1, 'soft': 1, 'what': 1, 'light': 1, 'through': 1, 'yonder': 1, 'window': 1, 'breaks': 1, 'It': 1, 'is': 3, 'the': 3, 'east': 1, 'and': 3, 'Juliet': 1, 'sun': 2, 'Arise': 1, 'fair': 1, 'kill': 1, 'envious': 1, 'moon': 1, 'Who': 1, 'already': 1, 'sick': 1, 'pale': 1, 'with': 1, 'grief': 1}


###Web Scraping

Ús d'un scropt o programa per cercar en pàgines web, extreure'n informació i cercar més pàgines web. Es pot veure què està lligat a què, extreure dades i estudies de plataformes sense aquesta capacitat, etc. Hi ha una mica de controvèrsia i s'ha de vigilar amb els termes de servei de les pàgines web i la publicació d'informació patentada o sota copyright.

####Beautiful Soup

Per fer cerques de *strings* el més recomanable és utilitzar el software/llibreria BeautifulSoup, de bs4.

In [ ]:
import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup

url = input('Enter - ')
html = urllib.request.urlopen(url).read()
soup = BeautifulSoup(html, 'html.parser')

#buscar tots els links (com tags per anar a altres pàgines des de la introduïda)
tags = soup('a')
for tag in tags:
  print(tag.get('href', None))

KeyboardInterrupt: ignored

###Entrega 1 de la setmana

Va sobre els primers temes:

You are to retrieve the following document using the HTTP protocol in a way that you can examine the HTTP Response headers.
* http://data.pr4e.org/intro-short.txt

There are three ways that you might retrieve this web page and look at the response headers:
* Preferred: Modify the socket1.py program to retrieve the above URL and print out the headers and data. Make sure to change the code to retrieve the above URL - the values are different for each URL.
* Open the URL in a web browser with a developer console or FireBug and manually examine the headers that are returned.
*Use the telnet program as shown in lecture to retrieve the headers and content.

In [ ]:
import socket

mysock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
mysock.connect(('data.pr4e.org', 80))
cmd = 'GET http://data.pr4e.org/intro-short.txt HTTP/1.0\r\n\r\n'.encode()
mysock.send(cmd)

while True:
  data = mysock.recv(512)
  if len(data)<1:
    break
  print(data.decode(), end='')
mysock.close()

HTTP/1.1 200 OK
Date: Sat, 27 Jun 2020 16:27:02 GMT
Server: Apache/2.4.18 (Ubuntu)
Last-Modified: Sat, 13 May 2017 11:22:22 GMT
ETag: "1d3-54f6609240717"
Accept-Ranges: bytes
Content-Length: 467
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Connection: close
Content-Type: text/plain

Why should you learn to write programs?

Writing programs (or programming) is a very creative 
and rewarding activity.  You can write programs for 
many reasons, ranging from making your living to solving
a difficult data analysis problem to having fun to helping
someone else solve a problem.  This book assumes that 
everyone needs to know how to program, and that once 
you know how to program you will figure out what you want 
to do with your newfound skills.  


###Entrega 2 de la setmana

**Scraping Numbers from HTML using BeautifulSoup** In this assignment you will write a Python program similar to http://www.py4e.com/code3/urllink2.py. The program will use **urllib** to read the HTML from the data files below, and parse the data, extracting numbers and compute the sum of the numbers in the file.

We provide two files for this assignment. One is a sample file where we give you the sum for your testing and the other is the actual data you need to process for the assignment.

* Sample data: http://py4e-data.dr-chuck.net/comments_42.html (Sum=2553)
* Actual data: http://py4e-data.dr-chuck.net/comments_721151.html (Sum ends with 6)

The file is a table of names and comment counts. You can ignore most of the data in the file except for lines like the following:

In [ ]:
<tr><td>Modu</td><td><span class="comments">90</span></td></tr>
<tr><td>Kenzie</td><td><span class="comments">88</span></td></tr>
<tr><td>Hubert</td><td><span class="comments">87</span></td></tr>

You are to find all the <$\text{span}$> tags in the file and pull out the numbers from the tag and sum the numbers.
Look at the sample code (https://www.py4e.com/code3/urllink2.py) provided. It shows how to find all of a certain kind of tag, loop through the tags and extract the various aspects of the tags.

In [ ]:
...
# Retrieve all of the anchor tags
tags = soup('a')
for tag in tags:
   # Look at the parts of a tag
   print 'TAG:',tag
   print 'URL:',tag.get('href', None)
   print 'Contents:',tag.contents[0]
   print 'Attrs:',tag.attrs

You need to adjust this code to look for **span** tags and pull out the text content of the span tag, convert them to integers and add them up to complete the assignment.

Sample Execution:

In [ ]:
$ python3 solution.py
Enter - http://py4e-data.dr-chuck.net/comments_42.html
Count 50
Sum 2...

####Solució:

In [ ]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import ssl
import re

# Ignore SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

url = input('Enter - ')
html = urlopen(url, context=ctx).read()
soup = BeautifulSoup(html, "html.parser")

# Retrieve all of the anchor tags
tags = soup('span')
total = []
count=0
for tag in tags:
    total.append(int(tag.contents[0]))
    count+=1
print('Count',count)
print('Sum',sum(total))

Enter - http://py4e-data.dr-chuck.net/comments_721151.html
Count 50
Sum 2606


###Entrega 3 de la setmana

In this assignment you will write a Python program that expands on http://www.py4e.com/code3/urllinks.py. The program will use urllib to read the HTML from the data files below, extract the href= vaues from the anchor tags, scan for a tag that is in a particular position relative to the first name in the list, follow that link and repeat the process a number of times and report the last name you find.

We provide two files for this assignment. One is a sample file where we give you the name for your testing and the other is the actual data you need to process for the assignment
* Sample problem: Start at http://py4e-data.dr-chuck.net/known_by_Fikret.html
Find the link at position 3 (the first name is 1). Follow that link. Repeat this process 4 times. The answer is the last name that you retrieve.
Sequence of names: Fikret Montgomery Mhairade Butchi Anayah
Last name in sequence: Anayah
* Actual problem: Start at: http://py4e-data.dr-chuck.net/known_by_Ty.html
Find the link at position 18 (the first name is 1). Follow that link. Repeat this process 7 times. The answer is the last name that you retrieve.
Hint: The first character of the name of the last page that you will load is: E

**Strategy**

The web pages tweak the height between the links and hide the page after a few seconds to make it difficult for you to do the assignment without writing a Python program. But frankly with a little effort and patience you can overcome these attempts to make it a little harder to complete the assignment without writing a Python program. But that is not the point. The point is to write a clever Python program to solve the program.

####Exemple

**Sample Execution**

Here is a sample execution of a solution:

The answer to the assignment for this execution is "Anayah".

In [ ]:
$ python3 solution.py
Enter URL: http://py4e-data.dr-chuck.net/known_by_Fikret.html
Enter count: 4
Enter position: 3
Retrieving: http://py4e-data.dr-chuck.net/known_by_Fikret.html
Retrieving: http://py4e-data.dr-chuck.net/known_by_Montgomery.html
Retrieving: http://py4e-data.dr-chuck.net/known_by_Mhairade.html
Retrieving: http://py4e-data.dr-chuck.net/known_by_Butchi.html
Retrieving: http://py4e-data.dr-chuck.net/known_by_Anayah.html

####Solució

In [ ]:
import urllib.request, urllib.parse, urllib.error
from bs4 import BeautifulSoup
import ssl
import re

# Ignore SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

url = input('Enter URL:')
html = urllib.request.urlopen(url, context=ctx).read()
soup = BeautifulSoup(html, 'html.parser')

count = input('Enter count:')
count = int(count)
pos = input('Enter position:')
pos = int(pos)
tags = soup('a')
tag = tags[0]
print(tag.get('href', None))
for i in range(count):
  tags = soup('a')
  tag = tags[pos-1]
  print('Retrievering:',tag.get('href', None))
  url = tag.get('href', None)
  html = urllib.request.urlopen(url, context=ctx).read()
  soup = BeautifulSoup(html, 'html.parser')
print(re.findall('by_(.*).html', tag.get('href', None)))

Enter URL:http://py4e-data.dr-chuck.net/known_by_Ty.html
Enter count:7
Enter position:18
http://py4e-data.dr-chuck.net/known_by_Siriol.html
Retrievering: http://py4e-data.dr-chuck.net/known_by_Masood.html
Retrievering: http://py4e-data.dr-chuck.net/known_by_Kenyon.html
Retrievering: http://py4e-data.dr-chuck.net/known_by_Darrius.html
Retrievering: http://py4e-data.dr-chuck.net/known_by_Gracie.html
Retrievering: http://py4e-data.dr-chuck.net/known_by_Kerris.html
Retrievering: http://py4e-data.dr-chuck.net/known_by_Hamish.html
Retrievering: http://py4e-data.dr-chuck.net/known_by_Elyse.html
['Elyse']


##Sessió 3

###XML

És l'acrònim per **eXtensible Markup Language**. Com el nom indica no és més que un llenguatge de programari i s'utilitza com a pont entre diferents llenguatges més comuns per fer *scripts*, com per exemple Python o Java.

El format general és, sense seguir indexació (ni espais en blanc quan no estem a *text content*):

\<start tag\> text content \</end tag\>

Poden haver atributs dins dels \<start tag\> com a \<start tag attribute="whatever"\>

### Parsing XML

For a single tag

In [ ]:
import xml.etree.ElementTree as ET
data = '''<person>
      <name>Arnau</name>
      <phone type="intl">
      +34 123 456 789
      </phone>
      <email hide="yes"/>
      </person>'''
tree = ET.fromstring(data)
print('Name:', tree.find('name').text)
print('Attr:', tree.find('email').get('hide'))

Name: Arnau
Attr: yes


For multiple tags

In [ ]:
import xml.etree.ElementTree as ET
input = '''<stuff>
  <users>
    <user x="2">
      <id>001</id>
      <name>Arnau</name>
    </user>
    <user x="7">
      <id>009</id>
      <name>Oriol</name>
    </user>
  </users>
</stuff>'''
stuff = ET.fromstring(input)
lst = stuff.findall('users/user')
print('User count:', len(lst))
for item in lst:
  print('Name:', item.find('name').text)
  print('ID:', item.find('id').text)
  print('Attribute:', item.get("x"))
        

User count: 2
Name: Arnau
ID: 001
Attribute: 2
Name: Oriol
ID: 009
Attribute: 7


###Entrega de la setmana

In this assignment you will write a Python program somewhat similar to http://www.py4e.com/code3/geoxml.py. The program will prompt for a URL, read the XML data from that URL using urllib and then parse and extract the comment counts from the XML data, compute the sum of the numbers in the file.

We provide two files for this assignment. One is a sample file where we give you the sum for your testing and the other is the actual data you need to process for the assignment.

* Sample data: http://py4e-data.dr-chuck.net/comments_42.xml (Sum=2553)
* Actual data: http://py4e-data.dr-chuck.net/comments_721153.xml (Sum ends with 18)

You do not need to save these files to your folder since your program will read the data directly from the URL. Note: Each student will have a distinct data url for the assignment - so only use your own data url for analysis.

The data consists of a number of names and comment counts in XML as follows:

In [ ]:
<comment>
  <name>Matthias</name>
  <count>97</count>
</comment>

####Solució

In [ ]:
import urllib.request, urllib.parse, urllib.error
import xml.etree.ElementTree as ET
import ssl

api_key = False
# If you have a Google Places API key, enter it here
# api_key = 'AIzaSy___IDByT70'
# https://developers.google.com/maps/documentation/geocoding/intro

if api_key is False:
    api_key = 42
    serviceurl = 'http://py4e-data.dr-chuck.net/xml?'
else :
    serviceurl = 'https://maps.googleapis.com/maps/api/geocode/xml?'

# Ignore SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE


address = input('Enter location: ')


parms = dict()
parms['address'] = address
if api_key is not False: parms['key'] = api_key
url = serviceurl + urllib.parse.urlencode(parms)
print('Retrieving', address)
uh = urllib.request.urlopen(address, context=ctx)

data = uh.read()
print('Retrieved', len(data), 'characters')

tree = ET.fromstring(data.decode())

counts = tree.findall('comments/comment')
count = 0
lst = []
for count_tag in counts:
  count+=1
  lst.append(int(count_tag.find('count').text))
print('Count:', count)
print('Sum:', sum(lst))

TypeError: ignored

##Sessió 4

###Extracting Data from JSON

JSON és una eina menys potent que XML a l'hora de contenir informació. Tot i així, gràcies a que amb una simple lçinia de codi es pot transformar la informació en una llista o diccionari de Python com els que ja s'han estudiat, permet un tractament de les dades extremadament més senzill.

In [ ]:
import json
input = '''[
{"id":"001",
"x":"2",
"nom":"Arnau"
},
{"id":"009",
"x":"7",
"nom":"Oriol"
}
]'''

info = json.loads(input)
#com que serà una llista (comença i acaba per [], si ho fes amb {} seria un diccionari) podem contar elements
print('User Count:', len(info))
for item in info:
  print('Name:', item['nom'])
  print('ID:', item['id'])
  print('Attr:', item['x'])

User Count: 2
Name: Arnau
ID: 001
Attr: 2
Name: Oriol
ID: 009
Attr: 7


###Entrega 1 de la setmana

In this assignment you will write a Python program somewhat similar to http://www.py4e.com/code3/json2.py. The program will prompt for a URL, read the JSON data from that URL using urllib and then parse and extract the comment counts from the JSON data, compute the sum of the numbers in the file and enter the sum below:
We provide two files for this assignment. One is a sample file where we give you the sum for your testing and the other is the actual data you need to process for the assignment.

* Sample data: http://py4e-data.dr-chuck.net/comments_42.json (Sum=2553)
* Actual data: http://py4e-data.dr-chuck.net/comments_721154.json (Sum ends with 54)

You do not need to save these files to your folder since your program will read the data directly from the URL. Note: Each student will have a distinct data url for the assignment - so only use your own data url for analysis.

El format de les dades facilitades és:

In [ ]:
{
  comments: [
    {
      name: "Matthias"
      count: 97
    },
    {
      name: "Geomer"
      count: 97
    }
    ...
  ]
}

SyntaxError: ignored

####Solució

In [ ]:
import urllib.request, urllib.parse, urllib.error
import xml.etree.ElementTree as ET
import ssl
import json


# Ignore SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

address = input('Enter location: ')

print('Retrieving', address)
uh = urllib.request.urlopen(address, context=ctx)

data = uh.read()
print('Retrieved', len(data), 'characters')

son = json.loads(data.decode())
fi = []
con = 0
for i in range(len(son["comments"])):
  fi.append(int(son["comments"][i]["count"]))
  con+=1
print('Count:', con)
print('Sum:', sum(fi))

Enter location: http://py4e-data.dr-chuck.net/comments_721154.json
Retrieving http://py4e-data.dr-chuck.net/comments_721154.json
Retrieved 2722 characters
Count: 50
Sum: 2554


###Entrega 2 de la setmana

**Calling a JSON API**

In this assignment you will write a Python program somewhat similar to http://www.py4e.com/code3/geojson.py. The program will prompt for a location, contact a web service and retrieve JSON for the web service and parse that data, and retrieve the first place_id from the JSON. A place ID is a textual identifier that uniquely identifies a place as within Google Maps.

**API End Points**

To complete this assignment, you should use this API endpoint that has a static subset of the Google Data:

http://py4e-data.dr-chuck.net/json?

This API uses the same parameter (address) as the Google API. This API also has no rate limit so you can test as often as you like. If you visit the URL with no parameters, you get "No address..." response.
To call the API, you need to include a key= parameter and provide the address that you are requesting as the address= parameter that is properly URL encoded using the urllib.parse.urlencode() function as shown in http://www.py4e.com/code3/geojson.py

Make sure to check that your code is using the API endpoint is as shown above. You will get different results from the geojson and json endpoints so make sure you are using the same end point as this autograder is using.

You can test to see if your program is working with a location of "South Federal University" which will have a place_id of "ChIJy0Uc1Zmym4gR3fmAYmWNuac".

The solution of the assignment will be the place_id for the *University of Pennsylvania*.


In [ ]:
import urllib.request, urllib.parse, urllib.error
import json
import ssl

api_key = False
# If you have a Google Places API key, enter it here
# api_key = 'AIzaSy___IDByT70'
# https://developers.google.com/maps/documentation/geocoding/intro

if api_key is False:
    api_key = 42
    serviceurl = 'http://py4e-data.dr-chuck.net/json?'
else :
    serviceurl = 'https://maps.googleapis.com/maps/api/geocode/json?'

# Ignore SSL certificate errors
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE


address = input('Enter location: ')

parms = dict()
parms['address'] = address
if api_key is not False: parms['key'] = api_key
url = serviceurl + urllib.parse.urlencode(parms)

print('Retrieving', url)
uh = urllib.request.urlopen(url, context=ctx)
data = uh.read().decode()
print('Retrieved', len(data), 'characters')

try:
  js = json.loads(data)
except:
  js = None

if not js or 'status' not in js or js['status'] != 'OK':
  print('==== Failure To Retrieve ====')
  print(data)

#print(json.dumps(js, indent=4)) #per veure com està tot en forma de diccionaris i llistes
id = js['results'][0]['place_id']
print(id)

Enter location: Universitat Autònoma de Barcelona
Retrieving http://py4e-data.dr-chuck.net/json?address=Universitat+Aut%C3%B2noma+de+Barcelona&key=42
Retrieved 2136 characters
ChIJY497myqUpBIRbYL-lRC9UYo


#Quart curs: Using Databases with Python

##Sessió 1

###Unicode Characters and Strings

In [ ]:
#recordem que la funció ord() ens dóna el valor numèric del terme segons els sistema ASCII
print(ord('*'))

42


Totes les *strings* de Python estan en UNICODE, per compartir-les amb altres llenguatges cal transformar-les en bytes (*to code*), i viceversa si es desitja seguir el procés contrari (*to decode*).

###Object Oriented Programming

Revisar conceptes:
* Class: gos (concepte)
* Instance/Object: gos (objecte real com podria ser la mascota d'algú conegut)
* Method/Message: bordar() seria un exemple. Acció que poden fer tots els gossos (com a concepte) però pel qual cal demanar a un en concret (com a objecte real) que ho executi.


In [ ]:
#creating a class
class PartyAnimal:
  x=0 #a bit of data in the class
  def party(self): #a method in the class
    self.x = self.x+1
    print('So far:', self.x)
an = PartyAnimal()
an.party()
an.party()

So far: 1
So far: 2


In [ ]:
#object life cycle
class PartyAnimal:
  x=0 #a bit of data in the class
  def __init__(self): #s'executarà tan aviat com es cridi a algo d'aquesta classe ("constructor")
    print('I am constructed')
  def party(self): #a method in the class
    self.x = self.x+1
    print('So far:', self.x)
  def __del__(self): #s'executarà tan aviat com es cridi a qualseol altra cosa que no és de la classe ("destructor")
    print('I am destructed', self.x)
an = PartyAnimal()
an.party()
an.party()
an = 42
print('an contains', an)

I am constructed
So far: 1
So far: 2
I am destructed 2
an contains 42


In [ ]:
#constructors can have additional parameters
class PartyAnimal:
  x = 0
  name = ""
  def __init__(self, z):
    self.name = z
    print(self.name, 'constructed')
  def party(self):
    self.x = self.x + 1
    print(self.name, 'animal count', self.x)
s = PartyAnimal("Sally")
s.party()
j = PartyAnimal("Jim")
j.party()
s.party()

Sally constructed
Sally animal count 1
Jim constructed
Jim animal count 1
Sally animal count 2


####Inheritance

Les classes creades poden reutilitzar-se de manera que es mantenen les funcions atribuides amb anterioritat i afegir-ne de noves.

In [ ]:
#com a exemple, FootballFan serà una extensió de PartyAnimal
class PartyAnimal:
  x = 0
  name = ""
  def __init__(self, z):
    self.name = z
    print(self.name, 'constructed')
  def party(self):
    self.x = self.x + 1
    print(self.name, 'animal count', self.x)
class FootballFan(PartyAnimal):
  points = 0
  def touchdown(self):
    self.points = self.points + 7
    self.party()
    print(self.name, 'points', self.points)
s = PartyAnimal("Sally")
s.party()
j = FootballFan("Jim")
j.party()
j.touchdown()

Sally constructed
Sally animal count 1
Jim constructed
Jim animal count 1
Jim points 7


##Sessió 2

###Databases


**Terminologia**

* Database: conté diverses *taules*
* Relació (o taula): conté *tuples* i *atributs*
* Tuple (o fila): conjunt de camps que generalment representen un "objecte" com una persona o una pista de música
* Atribut (també columna o camp): un de tants elements possibles de dades corresponents a l'objecte representat per la fila

**SQL**

Acrònim per Structured Query Language i és el llenguatge que s'utiltza per comunicar-se amb les Databases. Normalment serveix per:
* Crear taules
* Recuperar dades de les Databases
* Inserir/Actualitzar dades
* Eliminar dades

**Data Analysis Structure**

Tindrem el paper d'administradors amb SQLite Browser i el paper de developers utilitzant codi Python, amb els dos programes accedirem i modificarem dades a el fitxer Database. Al programa Python li donarem alguns inputs per tal d'obtenir outputs com per exemple fitxers en R, Excel o D3.js

###Using SQLite

Primer de tot cal instal·lar el programari i seguidament començar a posar en pràctica els següents passos per tal de familiaritzar-se amb el programa.

Per crear taules amb dades (els caràcters cal especificar-los) s'utilitza un codi com:
```
CREATE TABLE Users(
	name VARCHAR(128),
	email VARCHAR(128)
)
```

####SQL Insert

A part d'accedir a *Browse Data* i afegir manualment les coses, es pot executar la següent línia:
```
INSERT INTO Users(name,email) VALUES ('Kristin','kf@umich.edu')
```

####SQL Delete

Per eliminar alguna fila de la database:
```
DELETE FROM Users WHERE email='fred@umich.edu'
```

####SQL Update

Permet actualitzar algun camp (field) mitjançant un WHERE:
```
UPDATE Users SET name='Charles' WHERE email='csev@umich.edu'
```
Això canvia el nom que tenia atribuït el correu 'csev@umich.edu' pel nou nom 'Charles'

####SQL Retrieving records: Select

Permet recuperar el complet o un subgrup de les dades mitjançant l'execució de:
```
SELECT*FROM Users WHERE email='csev@umich.edu'
```

####SQL Sorting with ORDER BY

És com un *Select* però en aquest cas es pot decidir ordenar i fer-ho de manera ascendent o descendent.
```
SELECT*FROM Users ORDER BY email
SELECT*FROM Users ORDER BY name
```

###Entrega 1 de la setmana

Tota es fa amb SQLite, així que no s'insertarà codi aquí. Tot i així les intruccions són (només cal anar copiant):
```
CREATE TABLE Ages ( 
  name VARCHAR(128), 
  age INTEGER
)
```
```
DELETE FROM Ages;
INSERT INTO Ages (name, age) VALUES ('Teydren', 23);
INSERT INTO Ages (name, age) VALUES ('Payton', 36);
INSERT INTO Ages (name, age) VALUES ('Neive', 30);
INSERT INTO Ages (name, age) VALUES ('Ahmed', 18);
INSERT INTO Ages (name, age) VALUES ('Hollee', 16);
```
```
SELECT hex(name || age) AS X FROM Ages ORDER BY X
```
Find the first row in the resulting record set and enter the long string that looks like *53656C696E613333*.

**Solució**

El resultat hauria de ser **41686D65643138**

###Entrega 2 de la setmana


Recordeu que per tal que el codi funcioni primer hauríeu de descarregar mbox.txt i pujar-ho com a fitxer en aquest Colab (a la part esquerra, a *files*). En aquest mateix lloc trobareu el fitxer .sqlite creat, que és la resposta correcta a la tasca (triga una estona en carregar correctament, cal ser pacients: el conn.commit() és el que requereix més temps i es pot provar de fer cada certes iteracions o fora del loop).

**Counting Organizations**

This application will read the mailbox data (mbox.txt) and count the number of email messages per organization (i.e. domain name of the email address) using a database with the following schema to maintain the counts.
```
CREATE TABLE Counts (org TEXT, count INTEGER)
```
When you have run the program on mbox.txt upload the resulting database file above for grading.
If you run the program multiple times in testing or with dfferent files, make sure to empty out the data before each run.

You can use this code as a starting point for your application: http://www.py4e.com/code3/emaildb.py.

The data file for this application is the same as in previous assignments: http://www.py4e.com/code3/mbox.txt.

Because the sample code is using an UPDATE statement and committing the results to the database as each record is read in the loop, it might take as long as a few minutes to process all the data. The commit insists on completely writing all the data to disk every time it is called.

The program can be speeded up greatly by moving the commit operation outside of the loop. In any database program, there is a balance between the number of operations you execute between commits and the importance of not losing the results of operations that have not yet been committed.

In [ ]:
import sqlite3

conn = sqlite3.connect('org_count.sqlite')
cur = conn.cursor()

cur.execute('DROP TABLE IF EXISTS Counts')

cur.execute('''
CREATE TABLE Counts (org TEXT, count INTEGER)''')

fname = input('Enter file name: ')
if (len(fname) < 1): fname = 'mbox-short.txt'
fh = open(fname)
for line in fh:
    if not line.startswith('From: '): continue
    words = line.split()
    email = words[1]
    pieces = email.split('@')
    org = pieces[1]
    cur.execute('SELECT count FROM Counts WHERE org = ? ', (org,))
    row = cur.fetchone()
    if row is None:
        cur.execute('''INSERT INTO Counts (org, count)
                VALUES (?, 1)''', (org,))
    else:
        cur.execute('UPDATE Counts SET count = count + 1 WHERE org = ?',
                    (org,))
    conn.commit()

# https://www.sqlite.org/lang_select.html
sqlstr = 'SELECT org, count FROM Counts ORDER BY count DESC LIMIT 10'

for row in cur.execute(sqlstr):
    print(str(row[0]), row[1])

cur.close()

Enter file name: mbox.txt
iupui.edu 536
umich.edu 491
indiana.edu 178
caret.cam.ac.uk 157
vt.edu 110
uct.ac.za 96
media.berkeley.edu 56
ufp.pt 28
gmail.com 25
et.gatech.edu 17


##Sessió 3

###Designing Data Models

Com que les Databases amb SQL serien molt lentes d'escanejar si s'utilitzessin només noms (per exemple gèneres musicals). Es creen múltiples taules amb un link (id) que permet atribuir u número a cada clau important i poder-la relacionar només escanejant números, que és molt més fàcil (sobretot perquè són menys caràcters).

Un cop creats, l'operació JOIN a SQLite permet enllaçar-ho correctament, per exemple:
```
select Album.title, Artist.name from Album join Artist on Album.artist_id = Artist.id
```
Sense el ON es farien totes les combinacions possibles.

El JOIN complet seria per exemple:
```
select Track.title, Artist.name, Album.title, Genre.name from Track join Genre, Album join Artist on Track.genre_id = Genre.id and Track.album_id = Album.id and Album.artist_id = Artist.id
```

###Entrega de la setmana

**Musical Track Database**

This application will read an iTunes export file in XML and produce a properly normalized database with this structure:
```
CREATE TABLE Artist (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name    TEXT UNIQUE
);

CREATE TABLE Genre (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name    TEXT UNIQUE
);

CREATE TABLE Album (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    artist_id  INTEGER,
    title   TEXT UNIQUE
);

CREATE TABLE Track (
    id  INTEGER NOT NULL PRIMARY KEY 
        AUTOINCREMENT UNIQUE,
    title TEXT  UNIQUE,
    album_id  INTEGER,
    genre_id  INTEGER,
    len INTEGER, rating INTEGER, count INTEGER
);
```
If you run the program multiple times in testing or with different files, make sure to empty out the data before each run.

You can use this code as a starting point for your application: http://www.py4e.com/code3/tracks.zip. The ZIP file contains the Library.xml file to be used for this assignment. You can export your own tracks from iTunes and create a database, but for the database that you turn in for this assignment, only use the Library.xml data that is provided.

To grade this assignment, the program will run a query like this on your uploaded database and look for the data it expects to see:
```
SELECT Track.title, Artist.name, Album.title, Genre.name 
    FROM Track JOIN Genre JOIN Album JOIN Artist 
    ON Track.genre_id = Genre.ID and Track.album_id = Album.id 
        AND Album.artist_id = Artist.id
    ORDER BY Artist.name LIMIT 3
```

In [ ]:
import xml.etree.ElementTree as ET
import sqlite3

conn = sqlite3.connect('musical_trackdb.sqlite')
cur = conn.cursor()

# Make some fresh tables using executescript()
cur.executescript('''
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Track;
DROP TABLE IF EXISTS Genre;

CREATE TABLE Artist (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name    TEXT UNIQUE
);
 
CREATE TABLE Genre (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name    TEXT UNIQUE
);
 
CREATE TABLE Album (
    id  INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    artist_id  INTEGER,
    title   TEXT UNIQUE
);
 
CREATE TABLE Track (
    id  INTEGER NOT NULL PRIMARY KEY 
        AUTOINCREMENT UNIQUE,
    title TEXT  UNIQUE,
    album_id  INTEGER,
    genre_id  INTEGER,
    len INTEGER, rating INTEGER, count INTEGER
);
''')


fname = input('Enter file name: ')
if ( len(fname) < 1 ) : fname = 'Library.xml'

# <key>Track ID</key><integer>369</integer>
# <key>Name</key><string>Another One Bites The Dust</string>
# <key>Artist</key><string>Queen</string>
def lookup(d, key):
    found = False
    for child in d:
        if found : return child.text
        if child.tag == 'key' and child.text == key :
            found = True
    return None

stuff = ET.parse(fname)
all = stuff.findall('dict/dict/dict')
print('Dict count:', len(all))
for entry in all:
    if ( lookup(entry, 'Track ID') is None ) : continue

    name = lookup(entry, 'Name')
    artist = lookup(entry, 'Artist')
    album = lookup(entry, 'Album')
    genre = lookup(entry, 'Genre')
    count = lookup(entry, 'Play Count')
    rating = lookup(entry, 'Rating')
    length = lookup(entry, 'Total Time')

    if name is None or artist is None or album is None or genre is None: 
        continue

    print(name, artist, album, genre, count, rating, length)

    cur.execute('''INSERT OR IGNORE INTO Artist (name) 
        VALUES ( ? )''', ( artist, ) )
    cur.execute('SELECT id FROM Artist WHERE name = ? ', (artist, ))
    artist_id = cur.fetchone()[0]

    cur.execute('''INSERT OR IGNORE INTO Album (title, artist_id) 
        VALUES ( ?, ? )''', ( album, artist_id ) )
    cur.execute('SELECT id FROM Album WHERE title = ? ', (album, ))
    album_id = cur.fetchone()[0]

    cur.execute('''INSERT OR IGNORE INTO Genre (name)
        VALUES ( ? )''', (genre, ) )
    cur.execute('SELECT id from Genre WHERE name = ?', (genre, ))
    genre_id = cur.fetchone()[0]

    cur.execute('''INSERT OR REPLACE INTO Track
        (title, album_id, genre_id, len, rating, count) 
        VALUES ( ?, ?, ?, ?, ?, ? )''', 
        ( name, album_id, genre_id, length, rating, count ) )

    conn.commit()

Enter file name: Library.xml
Dict count: 404
Another One Bites The Dust Queen Greatest Hits Rock 55 100 217103
Asche Zu Asche Rammstein Herzeleid Industrial 79 100 231810
Beauty School Dropout Various Grease Soundtrack 48 100 239960
Black Dog Led Zeppelin IV Rock 109 100 296620
Bring The Boys Back Home Pink Floyd The Wall [Disc 2] Rock 33 100 87118
Circles Bryan Lee Blues Is Funk 54 60 355369
Comfortably Numb Pink Floyd The Wall [Disc 2] Rock 36 100 384130
Crazy Little Thing Called Love Queen Greatest Hits Rock 38 100 163631
Electric Funeral Black Sabbath Paranoid Metal 44 100 293015
Fat Bottomed Girls Queen Greatest Hits Rock 38 100 257515
For Those About To Rock (We Salute You) AC/DC Who Made Who Rock 84 100 353750
Four Sticks Led Zeppelin IV Rock 84 100 284421
Furious Angels Rob Dougan The Matrix Reloaded Soundtrack 54 100 330004
Gelle Bryan Lee Blues Is Blues/R&B 45 60 199836
Going To California Led Zeppelin IV Rock 100 100 215666
Grease Various Grease Soundtrack 42 100 205792
Hand

##Sessió 4

###Relacions many-to-many

En la sessió anterior s'han vist relacions one-to-many com per exemple cada track només podia pertànyer a un àlbum. Ara es veuran relacions com podrien ser autor-llibre, ja que pot ser que més d'un autor estigui atribuit al mateix llibre i que diferents llibres estiguin atribuits a un mateix autor.

S'acaba amb una taula sense cap *primary key* i múltiples *foreign keys* (dues en l'exemple autor-llibre). Això és perquè es crea una taula amb múltiples connexions one-to-many.

Per exemple:
```
CREATE TABLE User(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  name TEXT,
  email TEXT
);
CREATE TABLE Course(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
  title TEXT
);
CREATE TABLE Member(
  user_id INTEGER,
  course_id INTEGER,
  role INTEGER,
  PRIMARY KEY (user_id, course_id)
);
```
Ara li posem algunes dades:
```
INSERT INTO User (name, email) VALUES ('Jane', 'jane@tsugi.org');
INSERT INTO User (name, email) VALUES ('Ed', 'ed@tsugi.org');
INSERT INTO User (name, email) VALUES ('Sue', 'sue@tsugi.org');
INSERT INTO Course (title) VALUES ('Python');
INSERT INTO Course (title) VALUES ('SQL');
INSERT INTO Course (title) VALUES ('PHP');
```
Ara cal afegir les dades de membres:
```
INSERT INTO Member(user_id, course_id, role) VALUES (1,1,1);
INSERT INTO Member(user_id, course_id, role) VALUES (2,1,0);
INSERT INTO Member(user_id, course_id, role) VALUES (3,1,0);

INSERT INTO Member(user_id, course_id, role) VALUES (1,2,0);
INSERT INTO Member(user_id, course_id, role) VALUES (2,2,1);

INSERT INTO Member(user_id, course_id, role) VALUES (2,3,1);
INSERT INTO Member(user_id, course_id, role) VALUES (3,3,0);
```
Seleccionem certes dades i les ordenem (nota: role=1 és professorat i role=0 alumnat):
```
SELECT User.name, Member.role, Course.title
FROM User JOIN Member JOIN Course
ON Member.user_id=User.id AND Member.course_id=Course.id
ORDER BY Course.title, Member.role DESC, User.name
```

###Entrega de la setmana

This application will read roster data in JSON format, parse the file, and then produce an SQLite database that contains a User, Course, and Member table and populate the tables from the data file.

You can base your solution on this code: http://www.py4e.com/code3/roster/roster.py - this code is incomplete as you need to modify the program to store the role column in the Member table to complete the assignment.

Each student gets their own file for the assignment. Download this file and save it as roster_data.json. Move the downloaded file into the same folder as your roster.py program.

Once you have made the necessary changes to the program and it has been run successfully reading the above JSON data, run the following SQL command:
```
SELECT hex(User.name || Course.title || Member.role ) AS X FROM 
    User JOIN Member JOIN Course 
    ON User.id = Member.user_id AND Member.course_id = Course.id
    ORDER BY X
```
Find the first row in the resulting record set.

In [ ]:
import json
import sqlite3

conn = sqlite3.connect('rosterdb.sqlite')
cur = conn.cursor()

# Do some setup
cur.executescript('''
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Member;
DROP TABLE IF EXISTS Course;

CREATE TABLE User (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    name   TEXT UNIQUE
);

CREATE TABLE Course (
    id     INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    title  TEXT UNIQUE
);

CREATE TABLE Member (
    user_id     INTEGER,
    course_id   INTEGER,
    role        INTEGER,
    PRIMARY KEY (user_id, course_id)
)
''')

fname = input('Enter file name: ')
if len(fname) < 1:
    fname = 'roster_data.json'

# [
#   [ "Charley", "si110", 1 ],
#   [ "Mea", "si110", 0 ],

str_data = open(fname).read()
json_data = json.loads(str_data)

for entry in json_data:

    name = entry[0];
    title = entry[1];
    role = entry[2];

    print((name, title, role))

    cur.execute('''INSERT OR IGNORE INTO User (name)
        VALUES ( ? )''', ( name, ) )
    cur.execute('SELECT id FROM User WHERE name = ? ', (name, ))
    user_id = cur.fetchone()[0]

    cur.execute('''INSERT OR IGNORE INTO Course (title)
        VALUES ( ? )''', ( title, ) )
    cur.execute('SELECT id FROM Course WHERE title = ? ', (title, ))
    course_id = cur.fetchone()[0]

    cur.execute('''INSERT OR REPLACE INTO Member
        (user_id, course_id, role) VALUES ( ?, ?, ? )''',
        ( user_id, course_id, role ) )

    conn.commit()

Enter file name: roster_data.json
('Aislinn', 'si110', 1)
('Lida', 'si110', 0)
('Lucien', 'si110', 0)
('Koray', 'si110', 0)
('Alexa', 'si110', 0)
('Diane', 'si110', 0)
('Airidas', 'si110', 0)
('Aarman', 'si110', 0)
('Kitty', 'si110', 0)
('Faye', 'si110', 0)
('Nelly', 'si110', 0)
('Trudy', 'si110', 0)
('Cecily', 'si110', 0)
('Kile', 'si110', 0)
('Darren', 'si110', 0)
('Eabha', 'si110', 0)
('Rohit', 'si110', 0)
('Milana', 'si110', 0)
('Khalan', 'si110', 0)
('Cassia', 'si110', 0)
('Loui', 'si110', 0)
('Anthony', 'si110', 0)
('Richey', 'si110', 0)
('Fergie', 'si110', 0)
('Anastacia', 'si110', 0)
('Alighia', 'si110', 0)
('Ashton', 'si110', 0)
('Meri', 'si110', 0)
('Fay', 'si110', 0)
('Ellyce', 'si110', 0)
('Geena', 'si110', 0)
('Savannah', 'si110', 0)
('Atal', 'si110', 0)
('Efan', 'si110', 0)
('Martin', 'si110', 0)
('Ameelia', 'si110', 0)
('Aileigh', 'si110', 0)
('Nerea', 'si110', 0)
('Yadgor', 'si110', 0)
('Tru', 'si110', 0)
('Salman', 'si110', 0)
('Neo', 'si110', 0)
('Rui', 'si110', 0)
('

##Sessió 5

###Geocoding

Un cop havent vist els diferents passos i tractaments que es poden fer de fonts de dades, s'intentarà posar a la pràctica de manera conjunta. En general el procés equival a:

Data source $\xrightarrow{\text{gather}}$ Raw Database

$\hspace{4.2cm}\downarrow \text{clean}$

$\hspace{3.2cm}\text{Clean Database}$

Amb la DB neta es pot visualitzar les dades o bé analitzar-les.
              

En el cas de *Geocoding*, s'utilitzarà la API de Google per crear una base de dades .sqlite amb diverses geolocalitzacions. A aquesta s'accedirà amb un altre codi de Python que pot generar un fitxer JavaScript per crear un fitxer HTML i visualitzar les dades.

###Entrega de la setmana

**Retrieving GEOData**

Download the code from http://www.py4e.com/code3/geodata.zip - then unzip the file and edit where.data to add an address nearby where you live - don't reveal where you live. Then run the geoload.py to lookup all of the entries in where.data (including the new one) and produce the geodata.sqlite. Then run geodump.py to read the database and produce where.js. You can run the programs and then scroll back to take your screen shots when the program finishes. Then open where.html to visualize the map. Take screen shots as described below. Make sure that your added location shows in all three of your screen shots.

This is a relatively simple assignment. Don't take off points for little mistakes. If they seem to have done the assignment give them full credit. Feel free to make suggestions if there are small mistakes. Please keep your comments positive and useful. If you do not take grading seriously, the instructors may delete your response and you will lose points.

Per exemple jo vaig afegir 'Universitat Autonoma de Barcelona' havent vist que no hi era present i que no tenien accents.